//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaircutTurn
    {
        public long userId { get; set; }
        public System.DateTime arrivalDate { get; set; }
        public System.DateTime dateOfRequest { get; set; }
        public long Id { get; set; }
        public bool isCanceled { get; set; }
    
        public virtual User User { get; set; }
    }
}
